# =====================================
#
# Overrides docker-compose.yml to define Docker Sync volume for Mac users
#
# =====================================
version: "3"
services:
    php-fpm:
        volumes:
            - app-sf-sync:/var/www:nocopy
            - /var/www/var/cache
            - /var/www/var/logs
volumes:
    app-sf-sync:
        external: true
